# Generated by Django 5.0.6 on 2024-06-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default='zachee', max_length=100),
            preserve_default=False,
        ),
    ]
